import { sil_house } from './../config/page';
import service1 from "assets/images/services/services-img01.jpg"
import service2 from "assets/images/services/services-img02.jpg"
import service3 from "assets/images/services/services-img03.jpg"
import service4 from "assets/images/services/services-img04.jpg"
import service5 from "assets/images/services/services-img05.jpg"
import service6 from "assets/images/services/services-img06.jpg"
import service7 from "assets/images/services/services-img07.jpg"
import service8 from "assets/images/services/services-img08.jpg"
import aryan from "assets/images/reviews/Aryan.png"
import brain from "assets/images/reviews/brain.png"
import evelyn from "assets/images/reviews/evelyn.png"
import jose from "assets/images/reviews/jose.png"
import call_icon from "assets/images/info-call-img.png"
import email_icon from "assets/images/info-email-img.png"
import clack_icon from "assets/images/info-clock-img.png"
import sil_image1 from "assets/images/sil-images/sil-img01.jpg"
import sil_image2 from "assets/images/sil-images/sil-img02.jpg"
import sil_image3 from "assets/images/sil-images/sil-img03.jpg"
import sil_image4 from "assets/images/sil-images/sil-img04.jpg"
import community_participation1 from "assets/images/community/community-participation-img01.jpg"
import community_participation2 from "assets/images/community/community-participation-img02.jpg"
import community_participation3 from "assets/images/community/community-participation-img03.jpg"
import community_participation4 from "assets/images/community/community-participation-img04.jpg";
import capacity1 from "assets/images/capacity/capacity-building-img01.jpg"
import capacity2 from "assets/images/capacity/capacity-building-img02.jpg"
import capacity3 from "assets/images/capacity/capacity-building-img03.jpg"
import support1 from "assets/images/support/support-coordination-img01.jpg"
import support2 from "assets/images/support/support-coordination-img02.jpg"
import support3 from "assets/images/support/support-coordination-img03.jpg"
import assist_self1 from "assets/images/assist-self/assist-in-self-care-img01.jpg"
import assist_self2 from "assets/images/assist-self/assist-in-self-care-img02.jpg"
import assist_self3 from "assets/images/assist-self/assist-in-self-care-img03.jpg"
import assist_transport1 from "assets/images/assist-transport/assist-in-transport-img01.jpg"
import assist_transport2 from "assets/images/assist-transport/assist-in-transport-img.jpg"
import assist_transport3 from "assets/images/assist-transport/assist-in-transport-img02.jpg"
import assist_transport4 from "assets/images/assist-transport/assist-in-transport-img03.jpg"
import assist_transport5 from "assets/images/assist-transport/assist-in-transport-img04.jpg"
import normanhurst_img01 from "assets/images/Normanhurst/1.png"
import normanhurst_img02 from "assets/images/Normanhurst/2.png"
import normanhurst_img03 from "assets/images/Normanhurst/3.png"
import normanhurst_img04 from "assets/images/Normanhurst/4.png"
import normanhurst_img05 from "assets/images/Normanhurst/5.png"
import normanhurst_img06 from "assets/images/Normanhurst/6.png"
import normanhurst_img07 from "assets/images/Normanhurst/7.png"
import normanhurst_img08 from "assets/images/Normanhurst/8.png"
import normanhurst_img09 from "assets/images/Normanhurst/9.png"
import normanhurst_img10 from "assets/images/Normanhurst/10.png"
import property_img01 from "assets/images/2026/10/property-img01.jpg"
import property_img02 from "assets/images/2026/10/property-img02.jpg"
import property_img03 from "assets/images/2026/10/property-img03.jpg"
import property_img04 from "assets/images/2026/10/property-img04.jpg"
import property_img05 from "assets/images/2026/10/property-img05.jpg"
import property_img06 from "assets/images/2026/10/property-img06.jpg"
import property_img07 from "assets/images/2026/10/property-img07.jpg"
import property_img08 from "assets/images/2026/10/property-img08.jpg"
import property_img09 from "assets/images/2026/10/property-img09.jpg"
import property_img10 from "assets/images/2026/10/property-img10.jpg"
import property_img11 from "assets/images/2026/10/property-img11.jpg"
import property_img12 from "assets/images/2026/10/property-img12.jpg"
import property_img13 from "assets/images/2026/10/property-img13.jpg"
import property_img14 from "assets/images/2026/10/property-img14.jpg"
import property_img15 from "assets/images/2026/10/property-img15.jpg"
import property_img16 from "assets/images/2026/10/property-img16.jpg"
import property_img17 from "assets/images/2026/10/property-img17.jpg"
import property_img18 from "assets/images/2026/10/property-img18.jpg"
import property_img19 from "assets/images/2026/10/property-img19.jpg"
import property_img20 from "assets/images/2026/10/property-img20.jpg"
import property_img21 from "assets/images/2026/10/property-img21.jpg"
import property_img22 from "assets/images/2026/10/property-img22.jpg"
import gallery_img01 from "assets/images/2026/10/gallery-img01.jpg"
import gallery_img02 from "assets/images/2026/10/gallery-img02.jpg"
import gallery_img03 from "assets/images/2026/10/gallery-img03.jpg"
import gallery_img04 from "assets/images/2026/10/gallery-img04.jpg"
import gallery_img05 from "assets/images/2026/10/gallery-img05.jpg"
import gallery_img06 from "assets/images/2026/10/gallery-img06.jpg"
import home_modification_img01 from "assets/images/2026/10/home-modification-img01.jpg"
import gardening_house_yard_img01 from "assets/images/2026/09/home-repair-yard-maintenance-img01.jpg"
import gardening_house_yard_img02 from "assets/images/2026/10/gardening-house-and-yard-maintenance-img.jpg"
import gardening_house_yard_img03 from "assets/images/2026/09/home-repair-yard-maintenance-img03.jpg"
import gardening_house_yard_img04 from "assets/images/2026/09/home-repair-yard-maintenance-img04.jpg"
export {
    service1, service2, service3, service4,service5,service6,service7,service8,aryan, brain, evelyn,jose,
    email_icon,clack_icon,call_icon,sil_image1,sil_image2,sil_image3,sil_image4,community_participation1,
    community_participation2,community_participation3,community_participation4,capacity1,capacity2,capacity3,
    support1,support2,support3,assist_self1,assist_self2,assist_self3,assist_transport1,assist_transport2,
    assist_transport3,assist_transport4,assist_transport5,normanhurst_img01,normanhurst_img02,normanhurst_img03,normanhurst_img04,
    normanhurst_img05,normanhurst_img06,normanhurst_img07,normanhurst_img08,normanhurst_img09,normanhurst_img10,
    property_img01,property_img02,property_img03,property_img04,property_img05,property_img06,property_img07,
    property_img08,property_img09,property_img10,property_img11,property_img12,property_img13,property_img14,
    property_img15,property_img16,property_img17,property_img18,property_img19,property_img20,property_img21,
    property_img22,gallery_img01,gallery_img02,gallery_img03,gallery_img04,gallery_img05,gallery_img06,
    home_modification_img01,gardening_house_yard_img01,gardening_house_yard_img02,gardening_house_yard_img03,
    gardening_house_yard_img04,
}